=== huyqv-0507/crawl-data/build/web/WEB-INF/classes/centralregiondonate/xml/noodles.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.centralregiondonate.noodles.com"
           xmlns="http://www.centralregiondonate.noodles.com"
           elementFormDefault="qualified">
    <xs:element name="noodles" type="Noodles"/>
    <xs:complexType name="Noodles">
        <xs:sequence>
            <xs:element name="noodle" type="Noodle" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Noodle">
        <xs:sequence>
            <xs:element name="noodleName" type="xs:string"/>
            <xs:element name="price" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== huyqv-0507/crawl-data/build/web/WEB-INF/classes/centralregiondonate/xml/noodles.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<noodles xmlns="http://www.centralregiondonate.noodles.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.centralregiondonate.noodles.com noodles.xsd">
    <noodle>
        <noodleName>Thùng 30 gói mì Gấu Đỏ vị tôm và gà sợi phở 63g</noodleName>
        <price>75000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì Gấu Đỏ tôm chua cay 65g</noodleName>
        <price>75000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì chay Gấu Đỏ rau nấm 63g</noodleName>
        <price>68000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì Gấu Đỏ thịt bằm 64g</noodleName>
        <price>68000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì Gấu đỏ Bò bít tết hành phi 64g</noodleName>
        <price>75000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì Gấu Đỏ tôm và gà 63g</noodleName>
        <price>68000.0</price>
    </noodle>
    <noodle>
        <noodleName>Cháo Gấu Đỏ thịt bằm 50g thùng 50 gói</noodleName>
        <price>150000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì 3 Miền chay lá đa 65g</noodleName>
        <price>68000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì 3 Miền tôm chua cay 65g</noodleName>
        <price>75000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì 3 Miền tôm hùm 65g</noodleName>
        <price>68000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì Hảo Hảo tôm chua cay 75g</noodleName>
        <price>137500.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì Hảo 100 hương vị tôm chua cay 65g</noodleName>
        <price>109000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói vị bò Đệ Nhất gói 65g</noodleName>
        <price>260000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Bún giò heo Hằng Nga 75g</noodleName>
        <price>234000.0</price>
    </noodle>
    <noodle>
        <noodleName>Hủ tiếu Nam Vang Nhịp Sống Acecook 70g thùng 30 gói</noodleName>
        <price>250000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì trứng Safoco sợi nhỏ 500g thùng 20 gói</noodleName>
        <price>480000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì trứng Safoco cao cấp gói 500g thùng 10 gói</noodleName>
        <price>300000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì xào khô Hảo Hảo vị tôm hành 75g</noodleName>
        <price>150000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì Hảo Hảo tôm xào chua ngọt 75g</noodleName>
        <price>150000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì Hảo Hảo chay rau nấm Acecook 74g</noodleName>
        <price>150000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì 3 Miền Gold Reeva thịt bằm sa tế 75g</noodleName>
        <price>150000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì 3 Miền Gold Reeva chua cay Thái 75g</noodleName>
        <price>150000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì 3 Miền bò hầm rau thơm Gold Reeva 75g</noodleName>
        <price>150000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì 3 Miền Gold vị tôm chua cay đặc biệt 75g</noodleName>
        <price>150000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì 3 Miền vị bò sợi phở 65g</noodleName>
        <price>190000.0</price>
    </noodle>
    <noodle>
        <noodleName>Cháo sườn 3 Miền Reeva 50g thùng 50 gói</noodleName>
        <price>140000.0</price>
    </noodle>
    <noodle>
        <noodleName>Cháo 3 Miền Reeva thịt bằm 50g thùng 50 gói</noodleName>
        <price>140000.0</price>
    </noodle>
    <noodle>
        <noodleName>Cháo gà 3 Miền Reeva 50g (1t/50 gói)</noodleName>
        <price>120000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì Kokomi tôm chua cay 65g</noodleName>
        <price>70000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Omachi sốt bò hầm 80g thùng 30 gói</noodleName>
        <price>261000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Omachi sườn hầm ngũ quả 80g thùng 30 gói</noodleName>
        <price>261000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì Mama thịt heo bằm 60g</noodleName>
        <price>219000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì chay Mama vị rau củ 62g</noodleName>
        <price>220000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Vị Hương chay thập cẩm 65g thùng 30 gói</noodleName>
        <price>80000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì chay rau nấm Phúc Hảo 65g</noodleName>
        <price>120000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Jumbo Koreno vị kim chi Paldo gói 1kg thùng 10 gói</noodleName>
        <price>800000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì xào Colusa Miliket 85g</noodleName>
        <price>165000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì chay thập cẩm Tân Bình Phúc Hảo 60g</noodleName>
        <price>90000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Miliket tôm 80g thùng 30 gói</noodleName>
        <price>110000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì Miliket thập cẩm hải sản 70g</noodleName>
        <price>119000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì chay Miliket 70g thùng 30 gói</noodleName>
        <price>93000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Miliket giấy 75g thùng 30 gói</noodleName>
        <price>90000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì gà tím ăn liền chua cay Vifon 75g</noodleName>
        <price>170000.0</price>
    </noodle>
    <noodle>
        <noodleName>Miến vị thịt bằm Phú Hương 58g thùng 48 gói</noodleName>
        <price>400000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Hủ tiếu nam vang Vifon 65g</noodleName>
        <price>200000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Phở bò Vifon 65g</noodleName>
        <price>200000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì Đệ Nhất thịt bằm 82g</noodleName>
        <price>280000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói mì Lẩu Thái vị tôm 80g</noodleName>
        <price>250000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì ăn liền hương vị thịt xào Aone 85g</noodleName>
        <price>190000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì tô Aone 75g thùng 12 tô</noodleName>
        <price>110000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì chay rau nấm Lá Bồ Đề Bình Tây 63g thùng 30 gói</noodleName>
        <price>125000.0</price>
    </noodle>
    <noodle>
        <noodleName>Phở chay lá bồ đề Bình Tây</noodleName>
        <price>175000.0</price>
    </noodle>
    <noodle>
        <noodleName>Lốc 5 mì khô gà cay Samyang 140g</noodleName>
        <price>119000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì ly khô gà cay Samyang 70g</noodleName>
        <price>28000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì phô mai gà cay Samyang 140g</noodleName>
        <price>31000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì khô gà cay lạnh Samyang 151g</noodleName>
        <price>31000.0</price>
    </noodle>
    <noodle>
        <noodleName>Thùng 30 gói Mì trộn Ottogi vị tương đen Bắc Kinh gói 83g</noodleName>
        <price>349000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Bò Samyang 120g</noodleName>
        <price>27000.0</price>
    </noodle>
    <noodle>
        <noodleName>5 Mì Nongshim Soon Veggie Ramyun chay gói 112g</noodleName>
        <price>156000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì ly Kimchi Ramen Nongshim 75g</noodleName>
        <price>28000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Kimchi Ramen Nongshim 120g</noodleName>
        <price>28000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì tô Shin Cup NongShim 116g</noodleName>
        <price>40000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì ly Shin Cup Nongshim 75g</noodleName>
        <price>29000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Shin Ramyun Nongshim 120g</noodleName>
        <price>28000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Nongshim Ramyun 85g</noodleName>
        <price>22000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Neoguri Seafood Spicy Nongshim 120g</noodleName>
        <price>26000.0</price>
    </noodle>
    <noodle>
        <noodleName>Mì Cham-pong Ramyun Nongshim 124g</noodleName>
        <price>30000.0</price>
    </noodle>
    <noodle>
        <noodleName>Bánh snack Tako chips Nongshim 60g</noodleName>
        <price>26000.0</price>
    </noodle>
    <noodle>
        <noodleName>Bánh snack khoai lang Nongshim 55g</noodleName>
        <price>26000.0</price>
    </noodle>
    <noodle>
        <noodleName>Bánh snack tôm cay Nongshim 75g</noodleName>
        <price>26000.0</price>
    </noodle>
    <noodle>
        <noodleName>Bánh snack hương chuối Nongshim 45g (1t/30 gói)</noodleName>
        <price>610000.0</price>
    </noodle>
    <noodle>
        <noodleName>Bánh snack hành Nongshim 50g (1t/20 gói)</noodleName>
        <price>440000.0</price>
    </noodle>
    <noodle>
        <noodleName>Bánh xốp ngũ cốc nhân phô mai Samyang 80g (1t/20 gói)</noodleName>
        <price>950000.0</price>
    </noodle>
    <noodle>
        <noodleName>Tảo biển vị truyền thống Kimnori 40g (1t/20 gói)</noodleName>
