=== huyqv-0507/crawl-data/src/java/centralregiondonate/constants/appURL.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.centralregiondonate.appurl.com"
           xmlns="http://www.centralregiondonate.appurl.com"
           elementFormDefault="qualified">
    <xs:element name="urls" type="urls"/>
    <xs:complexType name="urls">
        <xs:sequence>
            <xs:element name="url" type="url" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="url">
        <xs:sequence>
            <xs:element name="rootUrl" type="xs:string"/>
            <xs:element name="categoriesUrl" type="categoriesUrl"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="categoriesUrl">
        <xs:sequence>
            <xs:element name="categoryUrl" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== huyqv-0507/crawl-data/src/java/centralregiondonate/constants/appURL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<urls xmlns="http://www.centralregiondonate.appurl.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.centralregiondonate.appurl.com appURL.xsd">
    <url>
        <rootUrl>
            https://www.pharmacity.vn/danh-muc-san-pham/thuoc-khong-ke-don/
        </rootUrl>
        <categoriesUrl>
            <categoryUrl>
                otc-thuoc-cam-lanh-ho
            </categoryUrl>
            <categoryUrl>
                otc-giam-dau-ha-sot
            </categoryUrl>
            <categoryUrl>
                otc-thuoc-da-lieu
            </categoryUrl>
            <categoryUrl>
                otc-thuoc-khang-di-ung
            </categoryUrl>
            <categoryUrl>
                otc-thuoc-khang-viem
            </categoryUrl>
            <categoryUrl>
                otc-thuoc-tieu-hoa
            </categoryUrl>
            <categoryUrl>
                otc-vitamin-khoang-chat
            </categoryUrl>
        </categoriesUrl>
    </url>
    <url>
        <rootUrl>http://thieulamua.com/danh-muc/</rootUrl>
        <categoriesUrl>
            <categoryUrl>thuc-pham-an-lien/</categoryUrl>
        </categoriesUrl>
    </url>
</urls>
